Asp.netCoreMVCCRUD/Models/ErrorViewModel.cs
using System;

namespace Asp.netCoreMVCCRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Asp.netCoreMVCCRUD/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.netCoreMVCCRUD.Models
{
    public class Funcionario
    {
        [Key]
        public int FuncionarioID { get; set; }
        
        [Column(TypeName ="nvarchar(250)")]
        [Required(ErrorMessage = "Nome é Obrigatório")]
        [DisplayName("Nome Completo")]
        public string NomeCompleto { get; set;}
        
        [Column(TypeName = "nvarchar(10)")]
        [DisplayName("Empresa")]
        public string EmpCode { get; set; }
        
        [Column(TypeName = "nvarchar(100)")]
        public string Cargo { get; set; }

        [Column(TypeName = "nvarchar(100)")]
        public string localizacao { get; set; }
    }
}

Asp.netCoreMVCCRUD/Models/FuncionarioContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.netCoreMVCCRUD.Models
{
    public class FuncionarioContext : DbContext
    {
        public FuncionarioContext()
        {

        }

        public FuncionarioContext(DbContextOptions<FuncionarioContext> options) : base(options)
        {

        }

        public DbSet<FuncionarioModel> Funcionarios { get; set; }

    }
}

Asp.netCoreMVCCRUD/Models/FuncionarioModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace Asp.netCoreMVCCRUD.Models
{
    public class FuncionarioModel
    {
        [Key]
        public int FuncionarioID { get; set; }
        
        [Column(TypeName ="nvarchar(250)")]
        [Required(ErrorMessage = "Nome é Obrigatório")]
        [DisplayName("Nome Completo")]
        public string NomeCompleto { get; set;}
        
        [Column(TypeName = "nvarchar(10)")]
        [DisplayName("Empresa")]
        public string EmpCode { get; set; }
        
        [Column(TypeName = "nvarchar(100)")]
        public string Cargo { get; set; }

        [Column(TypeName = "nvarchar(100)")]
        public string localizacao { get; set; }

        [DisplayName("E-mail")]
        [Required(ErrorMessage ="E-mail é Obrigatótio")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage ="Senha é Obrigatório")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [DisplayName("Lembre-me")]
        public bool Lembreme { get; set; }


        //public string ValidarLogin()
        //{
        //    FuncionarioContext obj = new FuncionarioContext();


        //    return false;

        //}
    }
}

Asp.netCoreMVCCRUD/Models/LoginModel.cs
using Asp.netCoreMVCCRUD.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace AspnetCoreMVCCRUD.Models
{
    public class LoginModel
    {
            
    }
}

Asp.netCoreMVCCRUD/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asp.netCoreMVCCRUD.Models;
using Microsoft.AspNetCore.Identity;

namespace Asp.netCoreMVCCRUD.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly FuncionarioContext _context;

        public FuncionarioController(FuncionarioContext context)
        {
            _context = context;
        }

        // GET: Funcionario
        public async Task<IActionResult> Index()
        {
            return View(await _context.Funcionarios.ToListAsync());
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ConectarLogin(FuncionarioModel usuario)
        {


            var userEmail = _context.Funcionarios.Where(f => f.Email == usuario.Email).Count();
            var userSenha = _context.Funcionarios.Where(f => f.Senha == usuario.Senha).Count();

            if (userSenha >= 1 && userEmail >= 1)
            {
                return RedirectToAction("index");
            }
            else
            {

                ViewBag.Message = "E-mail ou senha invalido";
                return View("Login");
            }
            

        }

        //GET: Funcionario/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new FuncionarioModel());
            else
                return View(_context.Funcionarios.Find(id));
        }

        // POST: Funcionario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("FuncionarioID,NomeCompleto,EmpCode,Cargo,localizacao,Email,Senha")] FuncionarioModel funcionario)
        {
            if (ModelState.IsValid)
            {
                if (funcionario.FuncionarioID == 0)
                    _context.Add(funcionario);
                else
                    _context.Update(funcionario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(funcionario);
        }

        // GET: Funcionario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var funcionario = await _context.Funcionarios.FindAsync(id);
            _context.Funcionarios.Remove(funcionario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Asp.netCoreMVCCRUD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Asp.netCoreMVCCRUD.Models;

namespace Asp.netCoreMVCCRUD.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Asp.netCoreMVCCRUD/Views/Funcionario/AddOrEdit.cshtml
@model Asp.netCoreMVCCRUD.Models.FuncionarioModel

@{
    ViewData["Title"] = "Create";
}


<h4>
    formulário de funcionário
</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="AddOrEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="FuncionarioID">
            </div>
            <div class="form-group">
                <label asp-for="NomeCompleto" class="control-label">Nome Completo</label>
                <input asp-for="NomeCompleto" class="form-control"S />
                <span asp-validation-for="NomeCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="EmpCode" class="control-label">Empresa</label>
                    <input asp-for="EmpCode" class="form-control" />
                    <span asp-validation-for="EmpCode" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Cargo" class="control-label"></label>
                    <input asp-for="Cargo" class="form-control" />
                    <span asp-validation-for="Cargo" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="localizacao" class="control-label"></label>
                <input asp-for="localizacao" class="form-control" />
                <span asp-validation-for="localizacao" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Asp.netCoreMVCCRUD/Views/Funcionario/Index.cshtml
@model IEnumerable<Asp.netCoreMVCCRUD.Models.FuncionarioModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Funcionarios Registrados </h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmpCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cargo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.localizacao)
            </th>
            <th>
                <a asp-action="AddOrEdit" class="btn  btn-outline-success"><i class="far fa-plus-square"></i> Cadastras Novo</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>              
                @Html.DisplayFor(modelItem => item.NomeCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmpCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cargo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.localizacao)
            </td>
            <td>
                <a asp-action="AddOrEdit" asp-route-id="@item.FuncionarioID"><i class="fa fa-marker fa-lg"></i></a>
                <a asp-action="Delete" asp-route-id="@item.FuncionarioID" class="text-danger ml-1" onclick="return confirm('Tem certeza que deseja excluir? ')"><i class="fa fa-trash-alt fa-lg"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

Asp.netCoreMVCCRUD/Views/Funcionario/Login.cshtml
@model FuncionarioModel
@{
    ViewData["Title"] = "Login";
}

<form asp-controller="Funcionario" asp-action="ConectarLogin">
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Login</h3>
                    <div class="d-flex justify-content-end social_icon">
                        <span><i class="fab fa-facebook-square"></i></span>
                        <span><i class="fab fa-google-plus-square"></i></span>
                        <span><i class="fab fa-twitter-square"></i></span>
                    </div>
                </div>
                <div class="card-body">
                    <form>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="Email" class="form-control" placeholder="E-Mail" asp-for="Email">
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" class="form-control" placeholder="Senha" asp-for="Senha">
                        </div>
                        <div class="row align-items-center remember">
                            <input type="checkbox">Lembrar-me
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Logar" class="btn float-right login">
                        </div>
                    </form>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center links">
                        Don't have an account?<a href="#">Sign Up</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a href="#">Forgot your password?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
      @if( ViewBag.Message != null)
      { 
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message")
            }
            
        </script>
       }  

Asp.netCoreMVCCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Asp.netCoreMVCCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp.netCoreMVCCRUD</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/98215f66de.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asp.netCoreMVCCRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Asp.netCoreMVCCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>